-- 招投标关键词导出记录表（按 Excel 结构 + 投标保证金）
CREATE TABLE IF NOT EXISTS `bidding_keyword_exports` (
    `id` VARCHAR(50) NOT NULL,
    `keyword` VARCHAR(100) NOT NULL,
    `record_type` VARCHAR(50) NULL,
    `sub_type` VARCHAR(100) NULL,
    `title` TEXT NULL,
    `province` VARCHAR(50) NULL,
    `city` VARCHAR(50) NULL,
    `district` VARCHAR(50) NULL,
    `cycle_info` VARCHAR(255) NULL,
    `publish_time_str` VARCHAR(50) NULL,
    `doc_fetch_time_str` VARCHAR(100) NULL,
    `project_no` VARCHAR(100) NULL,
    `project_budget` VARCHAR(255) NULL,
    `winning_amount` VARCHAR(255) NULL,
    `fund_source` VARCHAR(255) NULL,
    `bidding_method` VARCHAR(100) NULL,
    `evaluation_method` VARCHAR(100) NULL,
    `project_owner` VARCHAR(255) NULL,
    `owner_contact` VARCHAR(100) NULL,
    `owner_phone` VARCHAR(50) NULL,
    `winning_unit` VARCHAR(255) NULL,
    `winning_unit_contact` VARCHAR(100) NULL,
    `winning_unit_phone` VARCHAR(50) NULL,
    `bidding_agent` VARCHAR(255) NULL,
    `bid_deadline_str` VARCHAR(100) NULL,
    `detail_url` VARCHAR(500) NULL,
    `bid_bond` VARCHAR(255) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    INDEX `idx_bidding_keyword`(`keyword`),
    INDEX `idx_bidding_record_type`(`record_type`),
    INDEX `idx_bidding_province`(`province`),
    INDEX `idx_bidding_city`(`city`),
    INDEX `idx_bidding_project_no`(`project_no`),
    INDEX `idx_bidding_publish_time`(`publish_time_str`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
