-- CreateTable: 网站爬取信息表（招标/中标等爬取数据）
CREATE TABLE `scraping_infos` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `keyword` VARCHAR(200) NULL,
    `type` VARCHAR(100) NULL,
    `sub_type` VARCHAR(100) NULL,
    `title` VARCHAR(500) NULL,
    `province` VARCHAR(100) NULL,
    `city` VARCHAR(100) NULL,
    `district` VARCHAR(100) NULL,
    `detail` TEXT NULL,
    `published_at` DATETIME(3) NULL,
    `bid_doc_fetched_at` DATETIME(3) NULL,
    `project_no` VARCHAR(100) NULL,
    `project_budget` VARCHAR(100) NULL,
    `winning_amount` VARCHAR(100) NULL,
    `bidding_method` VARCHAR(100) NULL,
    `project_owner` VARCHAR(255) NULL,
    `owner_contact` VARCHAR(100) NULL,
    `owner_phone` VARCHAR(50) NULL,
    `winning_bidder` VARCHAR(255) NULL,
    `winning_bidder_contact` VARCHAR(100) NULL,
    `winning_bidder_phone` VARCHAR(50) NULL,
    `bidding_agent` VARCHAR(255) NULL,
    `bid_deadline` DATETIME(3) NULL,
    `detail_url` VARCHAR(1000) NULL,
    `product_related` VARCHAR(500) NULL,
    `reserve1` VARCHAR(500) NULL,
    `reserve2` VARCHAR(500) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `idx_scraping_keyword`(`keyword`),
    INDEX `idx_scraping_type`(`type`),
    INDEX `idx_scraping_province`(`province`),
    INDEX `idx_scraping_city`(`city`),
    INDEX `idx_scraping_published_at`(`published_at`),
    INDEX `idx_scraping_bid_deadline`(`bid_deadline`),
    INDEX `idx_scraping_created_at`(`created_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
