-- CreateTable (幂等性处理：如果表已存在则跳过)
CREATE TABLE IF NOT EXISTS `ai_model_configs` (
    `id` VARCHAR(50) NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `code` VARCHAR(100) NOT NULL,
    `provider` VARCHAR(50) NOT NULL,
    `model_name` VARCHAR(100) NOT NULL,
    `api_url` VARCHAR(500) NOT NULL,
    `api_key` VARCHAR(500) NOT NULL,
    `api_secret` VARCHAR(500) NULL,
    `max_tokens` INTEGER NOT NULL DEFAULT 2000,
    `temperature` DOUBLE NOT NULL DEFAULT 0.7,
    `top_p` DOUBLE NULL DEFAULT 0.9,
    `scene_type` VARCHAR(50) NOT NULL,
    `is_default` BOOLEAN NOT NULL DEFAULT false,
    `extra_config` JSON NULL,
    `supports_stream` BOOLEAN NOT NULL DEFAULT true,
    `supports_functions` BOOLEAN NOT NULL DEFAULT false,
    `supports_vision` BOOLEAN NOT NULL DEFAULT false,
    `cost_per_1k_tokens` DECIMAL(10, 6) NULL,
    `total_calls` INTEGER NOT NULL DEFAULT 0,
    `total_tokens` BIGINT NOT NULL DEFAULT 0,
    `is_active` BOOLEAN NOT NULL DEFAULT true,
    `is_available` BOOLEAN NOT NULL DEFAULT true,
    `last_check_at` DATETIME(3) NULL,
    `error_count` INTEGER NOT NULL DEFAULT 0,
    `sort_order` INTEGER NOT NULL DEFAULT 0,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `created_by` VARCHAR(50) NULL,
    `remark` TEXT NULL,

    UNIQUE INDEX `ai_model_configs_code_key`(`code`),
    INDEX `idx_scene_type`(`scene_type`),
    INDEX `idx_default_scene`(`is_default`, `scene_type`),
    INDEX `idx_is_active`(`is_active`),
    INDEX `idx_provider`(`provider`),
    INDEX `idx_sort_order`(`sort_order`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

